### ISSUE TITLE
add published param to "getJobs" request

### ISSUE THREAD

**Issue by makaiser** [aymen-mouelhi/workable-node#2]
Hi,
is it possible to add the "published" param to the getJobs method as an optional argument? like
`https://www.workable.com/spi/v3/accounts/groove-tech/jobs?state=published`

unfortunately the current getJobs method fetches ALL entries, even if they archived.

current code:

``` javascript
Workable.prototype.getJobs = function(subdomain, callback) {
    return this._get('/' + subdomain + '/jobs', callback);
};
```

**Comment by joe2son** [comment]
+1 please

**Comment by aymen-mouelhi** [comment]
Sure, I will add an options object as requested by @joe2son

**Comment by joe2son** [comment]
Well, you’re a massive legend.


On 27 Feb 2017, at 09:40, Aymen Mouelhi <notifications@github.com<mailto:notifications@github.com>> wrote:


Sure, I will add an options object as requested by @joe2son<https://github.com/joe2son>

**Comment by zeineb** [comment]
You rock dude !
