### ISSUE TITLE
Add options param to getJobs request, as well as groupBy

### ISSUE THREAD

**Issue by joe2son** [aymen-mouelhi/workable-node#4]
Related to open issue raised by @makaiser, please integrate an **{options}** object param to the **getJobs** request so we can filter-query specific jobs, e.g. {state: "published", location: {region_code: "IL"}, department: "Finance" ... }

Would also be awesome to have a groupBy param to group by location, department, etc.

Thanks.

**Comment by aymen-mouelhi** [comment]
Issue fixed in https://github.com/aymen-mouelhi/workable-node/commit/36f5f394b9281a1e577241933907983be58bccb6
